export const mockStations = [
  {
    id: '1',
    name: 'Westlands Mall',
    location: 'Westlands, Nairobi',
    partnerId: '4',
    partnerName: 'Location Partner',
    capacity: 20,
    availablePowerbanks: 15,
    status: 'active' as const,
    totalRentals: 450,
    revenue: 67500,
    createdAt: '2024-01-15',
  },
  {
    id: '2',
    name: 'JKIA Terminal 1',
    location: 'Jomo Kenyatta Airport',
    partnerId: '4',
    partnerName: 'Location Partner',
    capacity: 30,
    availablePowerbanks: 22,
    status: 'active' as const,
    totalRentals: 890,
    revenue: 133500,
    createdAt: '2024-01-10',
  },
  {
    id: '3',
    name: 'Two Rivers Mall',
    location: 'Runda, Nairobi',
    partnerId: '4',
    partnerName: 'Location Partner',
    capacity: 25,
    availablePowerbanks: 18,
    status: 'active' as const,
    totalRentals: 678,
    revenue: 101700,
    createdAt: '2024-02-01',
  },
  {
    id: '4',
    name: 'Sarit Centre',
    location: 'Westlands, Nairobi',
    partnerId: '4',
    partnerName: 'Location Partner',
    capacity: 15,
    availablePowerbanks: 3,
    status: 'maintenance' as const,
    totalRentals: 234,
    revenue: 35100,
    createdAt: '2024-01-20',
  },
];

export const mockPowerbanks = [
  {
    id: 'PB001',
    stationId: '1',
    stationName: 'Westlands Mall',
    batteryLevel: 95,
    status: 'available' as const,
    lastMaintenance: '2024-02-01',
  },
  {
    id: 'PB002',
    stationId: '1',
    stationName: 'Westlands Mall',
    batteryLevel: 100,
    status: 'available' as const,
    lastMaintenance: '2024-02-01',
  },
  {
    id: 'PB003',
    stationId: '1',
    stationName: 'Westlands Mall',
    batteryLevel: 45,
    status: 'rented' as const,
    lastMaintenance: '2024-01-28',
  },
  {
    id: 'PB004',
    stationId: '2',
    stationName: 'JKIA Terminal 1',
    batteryLevel: 88,
    status: 'available' as const,
    lastMaintenance: '2024-02-02',
  },
  {
    id: 'PB005',
    stationId: '2',
    stationName: 'JKIA Terminal 1',
    batteryLevel: 20,
    status: 'charging' as const,
    lastMaintenance: '2024-02-03',
  },
  {
    id: 'PB006',
    stationId: '4',
    stationName: 'Sarit Centre',
    batteryLevel: 0,
    status: 'maintenance' as const,
    lastMaintenance: '2024-01-15',
  },
];

export const mockRentals = [
  {
    id: 'R001',
    customerId: 'C001',
    customerName: 'John Kamau',
    customerEmail: 'john@example.com',
    powerbankId: 'PB003',
    stationId: '1',
    stationName: 'Westlands Mall',
    startTime: '2024-02-25T09:30:00Z',
    endTime: null,
    deposit: 500,
    hourlyRate: 50,
    status: 'active' as const,
  },
  {
    id: 'R002',
    customerId: 'C002',
    customerName: 'Mary Wanjiru',
    customerEmail: 'mary@example.com',
    powerbankId: 'PB010',
    stationId: '2',
    stationName: 'JKIA Terminal 1',
    startTime: '2024-02-25T08:00:00Z',
    endTime: '2024-02-25T11:30:00Z',
    deposit: 1000,
    hourlyRate: 100,
    roundedHours: 4,
    rentalCost: 400,
    refund: 600,
    status: 'completed' as const,
  },
  {
    id: 'R003',
    customerId: 'C003',
    customerName: 'Peter Ochieng',
    customerEmail: 'peter@example.com',
    powerbankId: 'PB015',
    stationId: '3',
    stationName: 'Two Rivers Mall',
    startTime: '2024-02-25T10:15:00Z',
    endTime: '2024-02-25T13:45:00Z',
    deposit: 500,
    hourlyRate: 50,
    roundedHours: 4,
    rentalCost: 200,
    refund: 300,
    status: 'completed' as const,
  },
];

export const mockUsers = [
  {
    id: '1',
    name: 'Super Admin',
    email: 'superadmin@chargebyte.io',
    role: 'super_admin' as const,
    status: 'active' as const,
    createdAt: '2023-12-01',
  },
  {
    id: '2',
    name: 'Admin User',
    email: 'admin@chargebyte.io',
    role: 'admin' as const,
    status: 'active' as const,
    createdAt: '2024-01-05',
  },
  {
    id: '3',
    name: 'Staff Member',
    email: 'staff@chargebyte.io',
    role: 'staff' as const,
    status: 'active' as const,
    createdAt: '2024-01-10',
  },
  {
    id: '4',
    name: 'Location Partner',
    email: 'partner@chargebyte.io',
    role: 'location_partner' as const,
    status: 'active' as const,
    createdAt: '2024-01-15',
    totalStations: 4,
    totalRevenue: 337800,
  },
  {
    id: '5',
    name: 'Advertising Partner',
    email: 'advertiser@chargebyte.io',
    role: 'ad_client' as const,
    status: 'active' as const,
    createdAt: '2024-01-20',
    activeCampaigns: 3,
    totalSpend: 45000,
  },
  {
    id: '6',
    name: 'Sponsor',
    email: 'sponsor@chargebyte.io',
    role: 'sponsor' as const,
    status: 'active' as const,
    createdAt: '2024-02-01',
    totalContributions: 500000,
    sponsoredLocations: 2,
  },
];

export const mockAdCampaigns = [
  {
    id: 'AD001',
    name: 'Summer Sale 2024',
    advertiser: 'Advertising Partner',
    advertiserId: '5',
    status: 'active' as const,
    impressions: 45670,
    clicks: 2340,
    startDate: '2024-02-01',
    endDate: '2024-03-31',
    budget: 25000,
    spent: 18500,
  },
  {
    id: 'AD002',
    name: 'Brand Awareness Campaign',
    advertiser: 'Advertising Partner',
    advertiserId: '5',
    status: 'active' as const,
    impressions: 32100,
    clicks: 1890,
    startDate: '2024-02-10',
    endDate: '2024-04-10',
    budget: 15000,
    spent: 8900,
  },
  {
    id: 'AD003',
    name: 'Product Launch',
    advertiser: 'Advertising Partner',
    advertiserId: '5',
    status: 'completed' as const,
    impressions: 28900,
    clicks: 3200,
    startDate: '2024-01-01',
    endDate: '2024-01-31',
    budget: 20000,
    spent: 19500,
  },
];

export const mockSponsorships = [
  {
    id: 'SP001',
    sponsor: 'Sponsor',
    sponsorId: '6',
    location: 'Kibera Community Center',
    amount: 300000,
    date: '2024-02-01',
    status: 'active' as const,
    stationsSponsored: 1,
    beneficiaries: 500,
  },
  {
    id: 'SP002',
    sponsor: 'Sponsor',
    sponsorId: '6',
    location: 'Mathare Youth Center',
    amount: 200000,
    date: '2024-02-15',
    status: 'active' as const,
    stationsSponsored: 1,
    beneficiaries: 350,
  },
];

export const mockAnalytics = {
  totalRentals: 2252,
  activeRentals: 23,
  totalRevenue: 337800,
  todayRevenue: 15600,
  totalStations: 4,
  activeStations: 3,
  totalPowerbanks: 95,
  availablePowerbanks: 58,
  totalUsers: 1567,
  activeUsers: 234,
  averageRentalDuration: 3.5,
  peakHours: ['12:00', '18:00'],
  topStations: [
    { name: 'JKIA Terminal 1', rentals: 890 },
    { name: 'Two Rivers Mall', rentals: 678 },
    { name: 'Westlands Mall', rentals: 450 },
  ],
};

export const mockRevenueShares = [
  {
    id: 'RS001',
    partnerId: '4',
    partnerName: 'Location Partner',
    period: '2024-02',
    totalRentals: 2252,
    rentalRevenue: 337800,
    sharePercentage: 20,
    partnerShare: 67560,
    platformShare: 270240,
    status: 'pending' as const,
  },
];
